### ISSUE TITLE
Diredfl cannot colorize socket file.

### ISSUE THREAD

**Issue by cireu** [purcell/diredfl#10]
For socket file, it will be displayed like "srwxrwxrwx". But regexps in current diredfl failed to match this suituation.

![image](https://user-images.githubusercontent.com/18224684/91115531-ffea3280-e6bc-11ea-809d-07eac319ed38.png)

Maybe we need to add prefix s to regexp.

**Comment by purcell** [comment]
Weird, I'd expect that the `s` would be red, at least, because such "rare" extensions are flagged by [this code](https://github.com/purcell/diredfl/blob/master/diredfl.el#L339-L340). For example, if I browse into `/dev` locally, I can see a bunch of lines that begin with a red `c` and then a grey `rw-rw-rw-`.

**Comment by condy0919** [comment]
I suspect you're the victim of https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-base.el#L444
